// Every bug a player reported becomes a scenario here, re-checked after every change.
// setup: code run inside the game; steps: what the player types; expect: code that must return true (or a string = failure reason).
const FIGHT = `(() => { const L = R.level, c = L.cells[L.y * L.w + L.x]; L.ch = mkChallenge('enc', c); L.ch.threats.forEach(t => t.hp = t.maxHp = 60); render(); })()`;
const PUDDLE = `R.level.cells[R.level.x].objs.push({ n: 'small puddle', i: '💧', traits: ['water'] })`;
module.exports = [
  { name: 'wet bloop: sounds never become objects; a puddle can be frozen into a weapon you keep',
    book: 'school', powers: ['ice'], setup: [PUDDLE, FIGHT],
    steps: ['What is that wet bloop sound?', 'I freeze the puddle into an ice sword and stab the monitor with it'],
    expect: `R.players[0].items.some(it => /sword|dagger|blade|icicle/.test(itemDef(it).n)) || 'no ice weapon in your hands'` },
  { name: 'icicle crash: using a crafted item until it breaks never crashes',
    book: 'school', powers: ['ice'], setup: [PUDDLE],
    steps: ['I freeze the puddle into an ice dagger and keep it', `#${FIGHT}`, 'I stab them with my ice dagger', 'I stab them again with the icicle thing', 'I stab them one more time with my dagger'],
    expect: `!R.level.log.some(l => /Something went wrong/.test(l.h)) || 'crash'` },
  { name: 'burn leaves something behind, and the game remembers it',
    book: 'candy', powers: ['fire'],
    steps: ['I burn the first thing I see here, just a little', 'What is left after I burned it?'],
    expect: `(R.level.kind === 'open' && (R.level.events || []).slice(-1).some(e => e.happened.length > 20)) || (R.level.kind !== 'open' ? 'page fell back to the offline map (AI busy?)' : 'no real answer')` },
  { name: 'helicopter: you cannot declare things into existence',
    book: 'jungle', powers: ['wind'],
    steps: ['I find a helicopter and fly out of here'],
    expect: `R.level.log.some(l => /Impossible/.test(l.h)) || 'helicopter allowed'` },
  { name: 'questions in a fight are answered and use no turn',
    book: 'jungle', powers: ['light'], setup: [FIGHT],
    steps: ['who is that and what do they want?'],
    expect: `(R.level.ch && R.level.ch.threats[0].hp === 60 && R.level.log.some(l => /No turn used/.test(l.h))) || 'turn used or no answer'` },
  { name: 'waiting passes time without showing numbers',
    book: 'sky', powers: ['bread'],
    steps: ['I wait', 'did anything happen while I waited?'],
    expect: `!R.level.log.some(l => /\\+10 HP/.test(l.h)) || 'shows numbers'` },
  { name: 'signature moves can be named and reused',
    book: 'jungle', powers: ['plants'],
    steps: ['I grow a thick wall of thorny vines around me', 'I call that Thorn Fort', 'Thorn Fort!'],
    expect: `(R.players[0].moves || []).some(m => m.name === 'Thorn Fort') || 'move not saved'` },
  { name: 'naming a move inside an action saves it and still does the action',
    book: 'jungle', powers: ['strength'], setup: [FIGHT],
    steps: ['I smash the ground so they fall over. I call that Quake Stomp'],
    expect: `((R.players[0].moves || []).some(m => m.name === 'Quake Stomp') && R.level.log.some(l => l.c === 'you' && !/call that/i.test(l.h))) || 'move not saved or action not done'` },
  { name: 'the goal is never announced while exploring',
    book: 'candy', powers: ['water'],
    steps: ['what do I see?', 'I look around carefully', 'I walk to the nearest place I can see', 'I listen carefully', 'I wait'],
    expect: `(!R.level.log.some(l => l.h.includes(OBJ[R.level.entry.o] ? OBJ[R.level.entry.o].n : '§§')) || !!R.level.ch) || 'goal name appeared'` },
];
